create database Note ； 
CREATE TABLE IF NOT EXISTS NOTE_USER(
    USER_MOBILE VARCHAR(11) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(20) NOT NULL,
    LOCK_FLG VARCHAR(1),
    CREATE_TIME CHAR(14) NOT NULL,
    LOGIN_TIME CHAR(14),
    UPDATE_TIME CHAR(14),
) ； 
CREATE TABLE IF NOT EXISTS USER_INFO(
    USER_MOBILE VARCHAR(11) NOT NULL PRIMARY KEY,
    SIGNATURE VARCHAR(255),
    FOLLOW VARCHAR(),
    FAN VARCHAR(),
    STAR VARCHAR(),
    USER_LEVEL CHAR(2),
    EXP CHAR (5),
    UPDATE_TIME CHAR(14),
) ；