create database Note ； 
USE Note;
DROP TABLE NOTE_USER;
CREATE TABLE IF NOT EXISTS NOTE_USER(
    USER_MOBILE VARCHAR(11) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(20) NOT NULL,
    LOCK_FLG VARCHAR(1),
    CREATE_TIME CHAR(14) NOT NULL,
    LOGIN_TIME CHAR(14),
    UPDATE_TIME CHAR(14));
DROP TABLE USER_INFO;
CREATE TABLE IF NOT EXISTS USER_INFO(
    USER_MOBILE VARCHAR(11) NOT NULL PRIMARY KEY,
    PROFILE_PHOTO VARCHAR(255),
    SIGNATURE VARCHAR(255) NOT NULL,
    FOLLOW VARCHAR(11) NOT NULL,
    FAN VARCHAR(11) NOT NULL,
    STAR VARCHAR(12) NOT NULL,
    USER_LEVEL CHAR(2) NOT NULL,
    EXP CHAR (5) NOT NULL,
    UPDATE_TIME CHAR(14)
);